---
- name: Replace Existing Props
  replace:
    path: "{{ path_to_cfg }}"
    regexp: '^{{ item.key }}.*'
    replace: '{{ item.key }}={{ item.value }}'
  loop: "{{ dict_to_changes|dict2items }}"
- name: Uncomment Existing Props
  replace:
    path: "{{ path_to_cfg }}"
    regexp: '^{{ comment_sym }}{{ item.key }}.*'
    replace: '{{ item.key }}={{ item.value }}'
  loop: "{{ dict_to_changes|dict2items }}"
- name: Add Props if not Exists
  replace:
    path: "{{ path_to_cfg }}"
    line: '{{ item.key }}={{ item.value }}'
  loop: "{{ dict_to_changes|dict2items }}"