---
galaxy_info:
  role_name: mass_changes
  author: yusmit
  description: Ansible role that mass changes
  company: SBT
  license: MIT
  min_ansible_version: 2.4.0
  github_branch: master
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 27
        - 28
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
        - wheezy
  galaxy_tags:
    - ubuntu
    - centos
    - debian
dependencies: []
